### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Nulllix** [Nulllix/simple_circular_progress_bar#5]
- [ ] Add tests.
- [ ] Add styles for line endings.
- [ ] Add sweep angle.
- [ ] Go to Flutter 3.0.
